#!/usr/bin/env bash
# context-mode diagnostic report
# Collects system, runtime, installation, and config info into a pasteable
# markdown report for GitHub issues.
#
# Usage:
#   bash scripts/ctx-debug.sh          # markdown to stdout
#   bash scripts/ctx-debug.sh --json   # (reserved, not yet implemented)
#
# Works on Linux, macOS, and Windows (Git Bash / MSYS2 / WSL).

CTX_DEBUG_VERSION="1.0.0"
set -uo pipefail  # NOT -e — we must never crash

# ─── Helpers ──────────────────────────────────────────────────────────────────

# Detect plugin root (directory containing this script's parent).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"
PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$SCRIPT_DIR/.." 2>/dev/null && pwd)}"

# safe_cmd CMD [ARGS...] — run a command with a 10-second timeout.
# Prints stdout on success or a failure marker on error.
safe_cmd() {
  local out rc
  if command -v timeout &>/dev/null; then
    out="$(timeout 10 "$@" 2>&1)" && rc=0 || rc=$?
  elif command -v gtimeout &>/dev/null; then
    out="$(gtimeout 10 "$@" 2>&1)" && rc=0 || rc=$?
  else
    out="$("$@" 2>&1)" && rc=0 || rc=$?
  fi
  if [ $rc -eq 0 ]; then
    printf '%s' "$out"
  elif [ $rc -eq 127 ]; then
    printf '[SKIP] command not found: %s' "$1"
  else
    printf '[FAIL] exit %d — %s' "$rc" "$out"
  fi
}

# safe_cmd_quiet — like safe_cmd but returns "" on failure (no marker).
safe_cmd_quiet() {
  local out
  if command -v timeout &>/dev/null; then
    out="$(timeout 10 "$@" 2>/dev/null)" || out=""
  elif command -v gtimeout &>/dev/null; then
    out="$(gtimeout 10 "$@" 2>/dev/null)" || out=""
  else
    out="$("$@" 2>/dev/null)" || out=""
  fi
  printf '%s' "$out"
}

# redact — replace API keys, tokens, secrets, and connection strings with ***REDACTED***.
redact() {
  sed -E \
    -e 's/(sk-[A-Za-z0-9_-]{4})[A-Za-z0-9_-]+/\1***REDACTED***/g' \
    -e 's/("(key|token|secret|password|apiKey|api_key|auth|credential|authorization)"[[:space:]]*:[[:space:]]*")([^"]{4})[^"]*/\1\3***REDACTED***/g' \
    -e 's/(ghp_[A-Za-z0-9]{4})[A-Za-z0-9]+/\1***REDACTED***/g' \
    -e 's/(ghu_[A-Za-z0-9]{4})[A-Za-z0-9]+/\1***REDACTED***/g' \
    -e 's/(xox[bpras]-[A-Za-z0-9]{4})[A-Za-z0-9-]+/\1***REDACTED***/g' \
    -e 's|(postgres(ql)?://[^:]+:)[^@]+(@)|\1***REDACTED***\3|g' \
    -e 's|(mongodb(\+srv)?://[^:]+:)[^@]+(@)|\1***REDACTED***\3|g' \
    -e 's|(mysql://[^:]+:)[^@]+(@)|\1***REDACTED***\3|g' \
    -e 's|(redis://[^:]+:)[^@]+(@)|\1***REDACTED***\3|g' \
    -e 's|(https?://[^:]+:)[^@]+(@)|\1***REDACTED***\3|g'
}

section() {
  printf '\n### %s\n\n' "$1"
}

check() {
  local label="$1" ok="$2"
  if [ "$ok" = "true" ]; then
    printf -- '- [x] %s\n' "$label"
  else
    printf -- '- [ ] %s\n' "$label"
  fi
}

kv() {
  printf -- '- **%s**: `%s`\n' "$1" "$2"
}

# detect_os — sets OS_TYPE to "macos", "linux", "windows", or "unknown".
detect_os() {
  case "$(uname -s 2>/dev/null)" in
    Darwin*)  OS_TYPE="macos"   ;;
    Linux*)
      if grep -qi microsoft /proc/version 2>/dev/null; then
        OS_TYPE="wsl"
      else
        OS_TYPE="linux"
      fi
      ;;
    MINGW*|MSYS*|CYGWIN*)  OS_TYPE="windows" ;;
    *)  OS_TYPE="unknown" ;;
  esac
}

# abbrev_path — shorten HOME to ~ for display.
abbrev_path() {
  local p="$1"
  if [ -n "${HOME:-}" ]; then
    printf '%s' "${p/#$HOME/~}"
  else
    printf '%s' "$p"
  fi
}

# config_file — check existence, print contents (redacted), limit to 60 lines.
config_file() {
  local label="$1" path="$2"
  local display
  display="$(abbrev_path "$path")"
  if [ -f "$path" ]; then
    printf -- '- **%s** (`%s`): exists\n' "$label" "$display"
    printf '  <details><summary>contents (redacted)</summary>\n\n  ```json\n'
    head -60 "$path" 2>/dev/null | redact
    printf '\n  ```\n  </details>\n'
  else
    printf -- '- **%s** (`%s`): not found\n' "$label" "$display"
  fi
}

# ─── Begin Report ─────────────────────────────────────────────────────────────

detect_os

NOW="$(date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || date '+%Y-%m-%d %H:%M:%S')"

cat <<HEADER
# context-mode diagnostic report

> Generated by \`ctx-debug.sh\` v${CTX_DEBUG_VERSION} at ${NOW}
HEADER

# ─── 1. System Info ──────────────────────────────────────────────────────────

section "1. System Info"

kv "OS type" "$OS_TYPE"
kv "uname -a" "$(safe_cmd_quiet uname -a | head -c 200)"
kv "Architecture" "$(safe_cmd_quiet uname -m)"

if [ "$OS_TYPE" = "macos" ]; then
  kv "macOS version" "$(safe_cmd_quiet sw_vers -productVersion) ($(safe_cmd_quiet sw_vers -buildVersion))"
elif [ "$OS_TYPE" = "linux" ] || [ "$OS_TYPE" = "wsl" ]; then
  if [ -f /etc/os-release ]; then
    kv "Distro" "$(safe_cmd_quiet bash -c '. /etc/os-release && echo "$PRETTY_NAME"')"
  fi
elif [ "$OS_TYPE" = "windows" ]; then
  kv "Windows ver" "$(safe_cmd_quiet cmd //c ver 2>/dev/null | tr -d '\r')"
fi

kv "Shell" "${SHELL:-unknown}"
[ -n "${BASH_VERSION:-}" ] && kv "Bash version" "$BASH_VERSION"
[ -n "${ZSH_VERSION:-}" ]  && kv "Zsh version" "$ZSH_VERSION"
kv "Locale" "LANG=${LANG:-unset}, LC_ALL=${LC_ALL:-unset}"

# ─── 2. Runtime Versions ─────────────────────────────────────────────────────

section "2. Runtime Versions"

# Node.js
NODE_VER="$(safe_cmd_quiet node --version)"
NODE_PATH_BIN="$(safe_cmd_quiet which node)"
if [ -n "$NODE_VER" ]; then
  kv "Node.js" "$NODE_VER"
  kv "node path" "$NODE_PATH_BIN"
  kv "execPath" "$(safe_cmd_quiet node -e 'console.log(process.execPath)')"

  # Install method heuristic
  NODE_INSTALL="unknown"
  case "$NODE_PATH_BIN" in
    */snap/*)       NODE_INSTALL="snap" ;;
    */.nvm/*)       NODE_INSTALL="nvm" ;;
    */.volta/*)     NODE_INSTALL="volta" ;;
    */.mise/*)      NODE_INSTALL="mise" ;;
    */.asdf/*)      NODE_INSTALL="asdf" ;;
    */.fnm/*)       NODE_INSTALL="fnm" ;;
    */homebrew/*|*/Homebrew/*|*/Cellar/*) NODE_INSTALL="brew" ;;
  esac
  kv "Node install method" "$NODE_INSTALL"
else
  printf -- '- [ ] **Node.js**: not found in PATH\n'
fi

# Bun
BUN_VER="$(safe_cmd_quiet bun --version)"
if [ -n "$BUN_VER" ]; then
  kv "Bun" "$BUN_VER"
  kv "bun path" "$(safe_cmd_quiet which bun)"
else
  BUN_HOME="${HOME:-}/.bun/bin/bun"
  if [ -x "$BUN_HOME" ]; then
    kv "Bun" "$("$BUN_HOME" --version 2>/dev/null || echo 'found but failed')"
    kv "bun path" "$BUN_HOME"
  else
    printf -- '- Bun: not installed\n'
  fi
fi

# Python
PY_VER="$(safe_cmd_quiet python3 --version || safe_cmd_quiet python --version)"
[ -n "$PY_VER" ] && kv "Python" "$PY_VER"

# Ruby
RUBY_VER="$(safe_cmd_quiet ruby --version)"
[ -n "$RUBY_VER" ] && kv "Ruby" "$RUBY_VER"

# npm
NPM_VER="$(safe_cmd_quiet npm --version)"
if [ -n "$NPM_VER" ]; then
  kv "npm" "$NPM_VER"
  kv "npm global root" "$(safe_cmd_quiet npm root -g | head -c 120)"
fi

# ─── 3. context-mode Installation ────────────────────────────────────────────

section "3. context-mode Installation"

# Version from package.json
PKG_JSON="$PLUGIN_ROOT/package.json"
if [ -f "$PKG_JSON" ]; then
  LOCAL_VER="$(safe_cmd_quiet node -e "console.log(require('$PKG_JSON').version)")"
  kv "Installed version" "${LOCAL_VER:-unknown}"
else
  LOCAL_VER=""
  printf -- '- [ ] package.json not found at plugin root\n'
fi

kv "Plugin root" "$(abbrev_path "$PLUGIN_ROOT")"

# Install method heuristic
INSTALL_METHOD="unknown"
case "$PLUGIN_ROOT" in
  */.claude/*)          INSTALL_METHOD="marketplace" ;;
  */node_modules/*)     INSTALL_METHOD="npm global/local" ;;
  *)                    INSTALL_METHOD="git clone / manual" ;;
esac
kv "Install method" "$INSTALL_METHOD"

# Key paths
check "build/ directory exists" "$([ -d "$PLUGIN_ROOT/build" ] && echo true || echo false)"
check "hooks/pretooluse.mjs exists" "$([ -f "$PLUGIN_ROOT/hooks/pretooluse.mjs" ] && echo true || echo false)"
check "hooks/sessionstart.mjs exists" "$([ -f "$PLUGIN_ROOT/hooks/sessionstart.mjs" ] && echo true || echo false)"
check "server.bundle.mjs exists" "$([ -f "$PLUGIN_ROOT/server.bundle.mjs" ] && echo true || echo false)"
check "cli.bundle.mjs exists" "$([ -f "$PLUGIN_ROOT/cli.bundle.mjs" ] && echo true || echo false)"

# npm latest
NPM_LATEST="$(safe_cmd_quiet npm view context-mode version 2>/dev/null)"
if [ -n "$NPM_LATEST" ]; then
  kv "npm latest" "$NPM_LATEST"
  if [ -n "$LOCAL_VER" ] && [ "$LOCAL_VER" != "$NPM_LATEST" ]; then
    printf -- '- ⚠️  **Update available**: %s → %s\n' "$LOCAL_VER" "$NPM_LATEST"
  fi
fi

# ─── 4. better-sqlite3 Native Module ─────────────────────────────────────────

section "4. better-sqlite3 Native Module"

# Find .node binary
SQLITE_NODE_FILE=""
if [ -d "$PLUGIN_ROOT/node_modules/better-sqlite3" ]; then
  SQLITE_NODE_FILE="$(find "$PLUGIN_ROOT/node_modules/better-sqlite3" -name '*.node' -type f 2>/dev/null | head -1)"
fi
check "better-sqlite3 .node binary exists" "$([ -n "$SQLITE_NODE_FILE" ] && echo true || echo false)"
[ -n "$SQLITE_NODE_FILE" ] && kv "Binary path" "$(abbrev_path "$SQLITE_NODE_FILE")"

# Require test
SQLITE_REQ="$(safe_cmd_quiet node -e "try{require('better-sqlite3');console.log('ok')}catch(e){console.log('FAIL: '+e.message)}" 2>&1)"
check "require('better-sqlite3') succeeds" "$([ "$SQLITE_REQ" = "ok" ] && echo true || echo false)"
[ "$SQLITE_REQ" != "ok" ] && printf -- '  > Error: `%s`\n' "$SQLITE_REQ"

# ABI version
NODE_ABI="$(safe_cmd_quiet node -e "console.log(process.versions.modules)")"
[ -n "$NODE_ABI" ] && kv "Node ABI version" "$NODE_ABI"

# ignore-scripts check
IGNORE_SCRIPTS="$(safe_cmd_quiet npm config get ignore-scripts)"
if [ "$IGNORE_SCRIPTS" = "true" ]; then
  printf -- '- ⚠️  `npm config get ignore-scripts` = **true** — this prevents native module compilation\n'
else
  check "npm ignore-scripts is false" "true"
fi

# ─── 5. Adapter Detection ────────────────────────────────────────────────────

section "5. Adapter Detection"

# Env var table
printf '| Variable | Value |\n|----------|-------|\n'

ADAPTER_VARS=(
  CONTEXT_MODE_PLATFORM
  CLAUDE_PROJECT_DIR CLAUDE_SESSION_ID
  GEMINI_PROJECT_DIR GEMINI_CLI
  OPENCLAW_HOME OPENCLAW_CLI
  KILO KILO_PID
  OPENCODE OPENCODE_PID
  CODEX_CI CODEX_THREAD_ID
  CURSOR_TRACE_ID CURSOR_CLI
  VSCODE_PID VSCODE_CWD
)

DETECTED_ADAPTER="none"
for var in "${ADAPTER_VARS[@]}"; do
  val="${!var:-}"
  if [ -n "$val" ]; then
    # Abbreviate long values
    display_val="$(printf '%s' "$val" | head -c 80)"
    printf '| `%s` | `%s` |\n' "$var" "$display_val"
  fi
done

# Detection logic (mirrors context-mode adapter selection)
if [ -n "${CONTEXT_MODE_PLATFORM:-}" ]; then
  DETECTED_ADAPTER="$CONTEXT_MODE_PLATFORM (explicit)"
elif [ -n "${CURSOR_TRACE_ID:-}${CURSOR_CLI:-}" ]; then
  DETECTED_ADAPTER="cursor"
elif [ -n "${VSCODE_PID:-}" ]; then
  DETECTED_ADAPTER="vscode-copilot"
elif [ -n "${CODEX_CI:-}${CODEX_THREAD_ID:-}" ]; then
  DETECTED_ADAPTER="codex"
elif [ -n "${GEMINI_PROJECT_DIR:-}${GEMINI_CLI:-}" ]; then
  DETECTED_ADAPTER="gemini-cli"
elif [ -n "${OPENCLAW_HOME:-}${OPENCLAW_CLI:-}" ]; then
  DETECTED_ADAPTER="openclaw"
elif [ -n "${KILO:-}${KILO_PID:-}" ]; then
  DETECTED_ADAPTER="kilocode"
elif [ -n "${OPENCODE:-}${OPENCODE_PID:-}" ]; then
  DETECTED_ADAPTER="opencode"
elif [ -n "${CLAUDE_SESSION_ID:-}${CLAUDE_PROJECT_DIR:-}" ]; then
  DETECTED_ADAPTER="claude-code"
fi

printf '\n'
kv "Active adapter (env)" "$DETECTED_ADAPTER"

# Detect installed adapters from config directories
HOME_DIR_EARLY="${HOME:-$USERPROFILE}"
INSTALLED=()
[ -d "$HOME_DIR_EARLY/.claude" ]                && INSTALLED+=("claude-code")
[ -d "$HOME_DIR_EARLY/.cursor" ] || [ -f ".cursor/mcp.json" ] && INSTALLED+=("cursor")
[ -d "$HOME_DIR_EARLY/.codex" ]                 && INSTALLED+=("codex")
[ -d "$HOME_DIR_EARLY/.gemini" ]                && INSTALLED+=("gemini-cli")
[ -d "$HOME_DIR_EARLY/.openclaw" ]              && INSTALLED+=("openclaw")
[ -d "$HOME_DIR_EARLY/.kiro" ]                  && INSTALLED+=("kiro")
[ -d "$HOME_DIR_EARLY/.config/opencode" ] || [ -f "opencode.json" ] || [ -d ".opencode" ] && INSTALLED+=("opencode")
[ -d "$HOME_DIR_EARLY/.config/kilo" ]           && INSTALLED+=("kilocode")
[ -d "$HOME_DIR_EARLY/.config/zed" ]            && INSTALLED+=("zed")
[ -f ".vscode/mcp.json" ]                       && INSTALLED+=("vscode-copilot")

if [ ${#INSTALLED[@]} -gt 0 ]; then
  kv "Installed adapters" "${INSTALLED[*]}"
else
  kv "Installed adapters" "none detected"
fi

# ─── 6. Config Files ─────────────────────────────────────────────────────────

section "6. Config Files"

HOME_DIR="${HOME:-$USERPROFILE}"
# Use git root for project-level configs, fall back to cwd
CWD="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

# Claude Code
config_file "Claude settings.json" "$HOME_DIR/.claude/settings.json"
config_file "Claude settings.local.json" "$HOME_DIR/.claude/settings.local.json"

# Gemini CLI
config_file "Gemini settings.json" "$HOME_DIR/.gemini/settings.json"

# Codex
config_file "Codex config.toml" "$HOME_DIR/.codex/config.toml"
config_file "Codex hooks.json" "$HOME_DIR/.codex/hooks.json"

# Cursor (project + global)
config_file "Cursor hooks.json (project)" "$CWD/.cursor/hooks.json"
config_file "Cursor mcp.json (project)" "$CWD/.cursor/mcp.json"
config_file "Cursor mcp.json (global)" "$HOME_DIR/.cursor/mcp.json"
config_file "Cursor hooks.json (global)" "$HOME_DIR/.cursor/hooks.json"

# VS Code Copilot
config_file "VS Code mcp.json (project)" "$CWD/.vscode/mcp.json"

# OpenCode
config_file "opencode.json (project)" "$CWD/opencode.json"
config_file "opencode.json (dotdir)" "$CWD/.opencode/opencode.json"
config_file "opencode.json (global)" "$HOME_DIR/.config/opencode/opencode.json"

# KiloCode
config_file "KiloCode settings.json" "$HOME_DIR/.config/kilo/settings.json"

# OpenClaw
config_file "OpenClaw openclaw.json" "$HOME_DIR/.openclaw/openclaw.json"
if [ -d "$HOME_DIR/.openclaw/extensions/context-mode" ]; then
  printf -- '- **OpenClaw extension dir**: exists (`~/.openclaw/extensions/context-mode/`)\n'
else
  printf -- '- **OpenClaw extension dir**: not found\n'
fi

# Kiro
config_file "Kiro mcp.json" "$HOME_DIR/.kiro/settings/mcp.json"
config_file "Kiro default agent" "$HOME_DIR/.kiro/agents/default.json"

# Zed
config_file "Zed settings.json" "$HOME_DIR/.config/zed/settings.json"

# ─── 7. Hook Validation ──────────────────────────────────────────────────────

section "7. Hook Validation"

# Collect hook files from plugin
HOOK_FILES=()
if [ -d "$PLUGIN_ROOT/hooks" ]; then
  while IFS= read -r f; do
    HOOK_FILES+=("$f")
  done < <(find "$PLUGIN_ROOT/hooks" -maxdepth 1 -type f -name '*.mjs' 2>/dev/null | sort)
fi

if [ ${#HOOK_FILES[@]} -gt 0 ]; then
  printf 'Hook files found in plugin:\n\n'
  for hf in "${HOOK_FILES[@]}"; do
    local_hf="$(abbrev_path "$hf")"
    if [ -x "$hf" ] || head -1 "$hf" 2>/dev/null | grep -q '#!/'; then
      printf -- '- [x] `%s`\n' "$local_hf"
    else
      printf -- '- [x] `%s` (not executable, but .mjs — OK for node)\n' "$local_hf"
    fi
  done
else
  printf -- '- [ ] No hook files found in `%s/hooks/`\n' "$(abbrev_path "$PLUGIN_ROOT")"
fi

# Check hooks.json in plugin root/hooks
HOOKS_JSON="$PLUGIN_ROOT/hooks/hooks.json"
if [ -f "$HOOKS_JSON" ]; then
  printf '\nhooks/hooks.json:\n'
  printf '```json\n'
  head -40 "$HOOKS_JSON" 2>/dev/null | redact
  printf '\n```\n'
fi

# Check for stale paths in Claude settings.json
CLAUDE_SETTINGS="$HOME_DIR/.claude/settings.json"
if [ -f "$CLAUDE_SETTINGS" ]; then
  STALE_HOOKS=()
  while IFS= read -r hookpath; do
    # Extract paths from the hooks section
    hookpath="$(printf '%s' "$hookpath" | sed -E 's/.*"([^"]+\.mjs)".*/\1/' | tr -d '"')"
    if [ -n "$hookpath" ] && [ ! -f "$hookpath" ]; then
      STALE_HOOKS+=("$hookpath")
    fi
  done < <(safe_cmd_quiet node -e "
    const s = require('$CLAUDE_SETTINGS');
    const hooks = s.hooks || {};
    for (const [event, arr] of Object.entries(hooks)) {
      if (Array.isArray(arr)) {
        for (const h of arr) {
          if (h.command) console.log(h.command);
          if (h.script) console.log(h.script);
        }
      }
    }
  " 2>/dev/null)

  if [ ${#STALE_HOOKS[@]} -gt 0 ]; then
    printf '\n**Stale hook paths detected:**\n'
    for sp in "${STALE_HOOKS[@]}"; do
      printf -- '- ⚠️  `%s` — file does not exist\n' "$sp"
    done
  else
    printf '\n'
    check "No stale hook paths in Claude settings.json" "true"
  fi
fi

# Hook registration completeness — check all required hooks are registered
if [ -f "$CLAUDE_SETTINGS" ] || [ -f "$HOOKS_JSON" ]; then
  printf '\n**Hook registration check:**\n'
  REQUIRED_HOOKS=("PreToolUse" "PostToolUse" "PreCompact" "SessionStart")
  for rh in "${REQUIRED_HOOKS[@]}"; do
    FOUND="false"
    # Check hooks.json
    if [ -f "$HOOKS_JSON" ] && grep -q "\"$rh\"" "$HOOKS_JSON" 2>/dev/null; then
      FOUND="true"
    fi
    # Check settings.json
    if [ -f "$CLAUDE_SETTINGS" ] && grep -q "\"$rh\"" "$CLAUDE_SETTINGS" 2>/dev/null; then
      FOUND="true"
    fi
    check "$rh registered" "$FOUND"
  done
fi

# Path separator check on Windows
if [ "$OS_TYPE" = "windows" ]; then
  if [ -f "$CLAUDE_SETTINGS" ]; then
    if grep -q '\\\\' "$CLAUDE_SETTINGS" 2>/dev/null; then
      printf -- '\n- ⚠️  **Backslash paths detected** in settings.json — use forward slashes on Windows\n'
    else
      check "No backslash paths in settings.json" "true"
    fi
  fi
fi

# ─── 8. SQLite / FTS5 Test ───────────────────────────────────────────────────

section "8. SQLite / FTS5 Test"

FTS5_RESULT="$(safe_cmd_quiet node -e "
  try {
    const Database = require('better-sqlite3');
    const db = new Database(':memory:');
    db.exec('CREATE VIRTUAL TABLE t USING fts5(c)');
    db.exec(\"INSERT INTO t VALUES('context-mode diagnostic test')\");
    const row = db.prepare('SELECT * FROM t WHERE t MATCH ?').get('diagnostic');
    if (row && row.c) { console.log('PASS'); } else { console.log('FAIL: no results'); }
    db.close();
  } catch (e) {
    console.log('FAIL: ' + e.message);
  }
" 2>&1)"

check "FTS5 in-memory test" "$([ "$FTS5_RESULT" = "PASS" ] && echo true || echo false)"
[ "$FTS5_RESULT" != "PASS" ] && printf -- '  > Error: `%s`\n' "$FTS5_RESULT"

# ─── 9. Executor Test ────────────────────────────────────────────────────────

section "9. Executor Test"

EXEC_RESULT="$(node -e "console.log('ok')" 2>&1)" && EXEC_RC=0 || EXEC_RC=$?
check "node subprocess spawn" "$([ "$EXEC_RESULT" = "ok" ] && [ "$EXEC_RC" -eq 0 ] && echo true || echo false)"
if [ "$EXEC_RESULT" != "ok" ] || [ "$EXEC_RC" -ne 0 ]; then
  printf '  > exit=%d, output: `%s`\n' "$EXEC_RC" "$EXEC_RESULT"
fi

# Shell executor
SHELL_EXEC="$(bash -c 'echo ok' 2>&1)" && SHELL_RC=0 || SHELL_RC=$?
check "bash subprocess spawn" "$([ "$SHELL_EXEC" = "ok" ] && [ "$SHELL_RC" -eq 0 ] && echo true || echo false)"

# ─── 10. Process Check ───────────────────────────────────────────────────────

section "10. Process Check"

# Portable process listing — exclude dashboard, esbuild, wrangler, workerd, grep
if command -v ps &>/dev/null; then
  CTX_PROCS="$(ps aux 2>/dev/null | grep '[c]ontext-mode' | grep -v -E 'context-mode-dashboard|esbuild|wrangler|workerd|grep' || true)"
  CTX_COUNT="$(printf '%s' "$CTX_PROCS" | grep -c . 2>/dev/null || echo 0)"
else
  CTX_PROCS=""
  CTX_COUNT="0"
fi

kv "Running context-mode processes" "$CTX_COUNT"

if [ "$CTX_COUNT" -gt 0 ]; then
  printf '\n```\n%s\n```\n' "$(printf '%s' "$CTX_PROCS" | head -10)"
fi

if [ "$CTX_COUNT" -gt 3 ]; then
  printf -- '- ⚠️  Multiple context-mode processes detected — possible orphans\n'
fi

# ─── 11. Session Databases ───────────────────────────────────────────────────

section "11. Session Databases"

# Check session dirs for all adapters
SESSION_DIRS=(
  "$HOME_DIR/.claude/context-mode/sessions"
  "$HOME_DIR/.cursor/context-mode/sessions"
  "$HOME_DIR/.codex/context-mode/sessions"
  "$HOME_DIR/.gemini/context-mode/sessions"
  "$HOME_DIR/.openclaw/context-mode/sessions"
  "$HOME_DIR/.kiro/context-mode/sessions"
)
TOTAL_DB_COUNT=0
for SESSION_DIR in "${SESSION_DIRS[@]}"; do
  if [ -d "$SESSION_DIR" ]; then
    DB_FILES="$(find "$SESSION_DIR" -name '*.db' -type f 2>/dev/null)"
    DB_COUNT="$(printf '%s' "$DB_FILES" | grep -c . 2>/dev/null || echo 0)"
    if [ "$DB_COUNT" -gt 0 ]; then
      TOTAL_DB_COUNT=$((TOTAL_DB_COUNT + DB_COUNT))
      if command -v du &>/dev/null; then
        DB_SIZE="$(printf '%s' "$DB_FILES" | xargs du -ch 2>/dev/null | tail -1 | cut -f1)"
      else
        DB_SIZE="unknown"
      fi
      kv "$(abbrev_path "$SESSION_DIR")" "$DB_COUNT files, $DB_SIZE"
    fi
  fi
done
if [ "$TOTAL_DB_COUNT" -eq 0 ]; then
  printf -- '- No session databases found in any adapter directory\n'
else
  kv "Total session DBs" "$TOTAL_DB_COUNT"
fi

# ─── 12. Environment Variables ───────────────────────────────────────────────

section "12. Environment Variables"

# Temp dirs
kv "TMPDIR" "${TMPDIR:-unset}"
kv "TEMP" "${TEMP:-unset}"
kv "TMP" "${TMP:-unset}"

# Node config
kv "NODE_OPTIONS" "${NODE_OPTIONS:-unset}"
kv "NODE_PATH" "${NODE_PATH:-unset}"
kv "NODE_EXTRA_CA_CERTS" "${NODE_EXTRA_CA_CERTS:-unset}"

# SSL
kv "SSL_CERT_FILE" "${SSL_CERT_FILE:-unset}"
kv "CURL_CA_BUNDLE" "${CURL_CA_BUNDLE:-unset}"

# Auth (redacted)
if [ -n "${SSH_AUTH_SOCK:-}" ]; then
  kv "SSH_AUTH_SOCK" "yes (set)"
else
  kv "SSH_AUTH_SOCK" "unset"
fi

# context-mode specific
kv "CONTEXT_MODE_SESSION_SUFFIX" "${CONTEXT_MODE_SESSION_SUFFIX:-unset}"
kv "CONTEXT_MODE_NODE" "${CONTEXT_MODE_NODE:-unset}"

# PATH (abbreviated — show key directories)
printf -- '- **PATH** (key dirs):\n'
IFS=':' read -ra PATH_PARTS <<< "${PATH:-}"
SHOWN=0
for p in "${PATH_PARTS[@]}"; do
  case "$p" in
    *node*|*npm*|*nvm*|*volta*|*mise*|*bun*|*python*|*ruby*|*homebrew*|*Homebrew*|*/usr/local/bin|*/usr/bin|*/.local/bin|*snap*)
      printf -- '  - `%s`\n' "$(abbrev_path "$p")"
      SHOWN=$((SHOWN + 1))
      ;;
  esac
  [ "$SHOWN" -ge 15 ] && break
done
[ "$SHOWN" -eq 0 ] && printf '  - (no notable dirs detected)\n'
printf -- '  - ... (%d total entries)\n' "${#PATH_PARTS[@]}"

# ─── Footer ──────────────────────────────────────────────────────────────────

printf '\n---\n\n'
printf '> Paste this report into your GitHub issue: https://github.com/mksglu/context-mode/issues/new\n'
